# Generated by Django 2.2 on 2020-10-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvCompare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_jiradb',
            name='file_name',
            field=models.FileField(upload_to='csvCompare'),
        ),
    ]
