# Generated by Django 2.2 on 2020-10-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kundeninfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=100)),
                ('E_Mail', models.EmailField(max_length=200)),
                ('Benutzername', models.CharField(max_length=100)),
            ],
        ),
    ]
