# Generated by Django 2.2 on 2020-10-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KundenInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kundeninfo_Portal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullnameP', models.CharField(max_length=100)),
                ('E_MailP', models.EmailField(max_length=200)),
                ('BenutzernameP', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Kundeninfo',
            new_name='Kundeninfo_Jira',
        ),
    ]
